apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ printf "%s-%s" .Values.namespace (toString .Values.namespaceSuffix) }}
  labels:
    app: {{ .Values.app }}
spec:
  ports:
  - name: {{ .Values.app }}
    protocol: TCP
    port: 1099
    targetPort: 1099
    protocol: TCP
    port: 1099 #60000
    targetPort: 1099 #60000
  clusterIP: None
  selector:
    app: {{ .Values.app }}
