apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ printf "%s-%s" .Values.namespace (toString .Values.namespaceSuffix) }}
  name: perf-jmeter-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: {{ if eq .Values.destination.target "aws" }}efs-csi-default{{ else }}local-storage{{ end }}

