apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.serviceAccount.roleBinding }}
  namespace: {{ printf "%s-%s" .Values.namespace (toString .Values.namespaceSuffix) }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}
    namespace: {{ printf "%s-%s" .Values.namespace (toString .Values.namespaceSuffix) }}
roleRef:
  kind: Role
  name: {{ .Values.serviceAccount.role }}
  apiGroup: rbac.authorization.k8s.io

